# Some NumPy Functions:

## Creating Numpy Arrays:

1. np.array([1,2,3,4]) <--- 1d array
2. np.array([[1,2,3], [4,5,6]]) <--- 2d array
3. We can use dtype to change data type like np.array([1,2,3], dtype=float)
4. np.arange(start, stop, step) i.e np.arange(1, 11, 2) creates an array like [1,3,5,7,9]
5. We can also use reshape to change the shape of created array like:<br>
np.arange(10).reshape(2,5) this will first create a 1d array with 10 elements and then convert it into matrix of 2x5. code example:

In [2]:
import numpy as np

arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

6. np.ones((3,4)) <--- it creates a array of 3x4 size with only ones
7. np.zeros((3,4)) <--- same as above but creates matix having zero only
8. np.random.random((3,4)) <--- creates a array of given size with random values
9. np.linspace(start, end, number of elements in array) it is used for creating an array having values with equal distance from eachother. code example:

In [6]:
arr1 = np.linspace(-10, 10, 10)
arr1

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

By default it has float vlaues to convert it into int just used a new parameter dtype like:

In [5]:
arr1 = np.linspace(-10, 10, 10, dtype=int)
arr1

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

## Array Attributes:

1. ndim gives the dimension of array
2. shape gives the shape of array
3. size gives the number of elements in the array
4. itemsize gives the bytes stored for int32 we use 4 bytes and for float64 and int63 we use 8 bytes of memory
5. dtype used to check the datatype 
6. astype can be used to convert a int value into float vice versa


## Array Operation:

### 1. Scalar Operations
Scalar operations involve a vector and a single numeric value. The scalar value is applied to every single element inside the vector individually.

* **Scalar Addition:** Adds the scalar value to every element.
  ```python
  v + 5
  ```
* **Scalar Subtraction:** Subtracts the scalar value from every element.
  ```python
  v - 2
  ```
* **Scalar Multiplication:** Multiplies every element by the scalar value.
  ```python
  v * 3
  ```
* **Scalar Division:** Divides every element by the scalar value.
  ```python
  v / 2
  ```

### 2. Vector-to-Vector Operations
These operations involve two or more vectors. The math is performed element-by-element between corresponding positions, or it aggregates the vectors into a geometric result.

* **Vector Addition:** Adds corresponding elements of two equal-length vectors.
  ```python
  a + b
  ```
* **Vector Subtraction:** Subtracts corresponding elements of two equal-length vectors.
  ```python
  a - b
  ```
* **Element-wise Multiplication (Hadamard Product):** Multiplies corresponding elements together.
  ```python
  a * b
  ```
* **Element-wise Division:** Divides corresponding elements of the first vector by the second.
  ```python
  a / b
  ```
* **Dot Product:** Multiplies corresponding elements and returns the sum of those products as a single scalar.
  ```python
  np.dot(a, b)  # Or: a @ b
  ```
* **Cross Product:** Computes a new vector perpendicular to two vectors (primarily used in 3D space).
  ```python
  np.cross(a, b)
  ```
* **Vector Norm (Magnitude):** Calculates the spatial length or Euclidean distance of the vector.
  ```python
  np.linalg.norm(a)
  ```


## Array Stacking in NumPy

Stacking joins a sequence of existing arrays along a new or specified axis. The arrays must have matching shapes along the stacking dimensions.

### 1. Horizontal Stacking (`np.hstack`)
Stacks arrays row-by-row (column-wise). It is equivalent to concatenation along the second axis (`axis=1`).

```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacks horizontally
result = np.hstack((a, b))
# Output: [1, 2, 3, 4, 5, 6]
```

### 2. Vertical Stacking (`np.vstack`)
Stacks arrays column-by-column (row-wise). It is equivalent to concatenation along the first axis (`axis=0`).

```python
# Stacks vertically into a 2D matrix
result = np.vstack((a, b))
# Output: 
# [[1, 2, 3],
#]
```

### 3. Depth Stacking (`np.dstack`)
Stacks arrays along the third axis (depth/layers). This turns 2D arrays into 3D arrays.

```python
# Stacks along the 3rd dimension
result = np.dstack((a, b))
```


## Array Splitting in NumPy

Splitting breaks a single array into multiple smaller sub-arrays. You can split an array evenly or at specific index positions.

### 1. Horizontal Splitting (`np.hsplit`)
Splits an array horizontally (column-wise). For 2D matrices, it cuts the columns apart.

```python
import numpy as np

# A 2x4 matrix
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

# Split into 2 equal parts along the columns
left, right = np.hsplit(arr, 2)
```

### 2. Vertical Splitting (`np.vsplit`)
Splits an array vertically (row-wise). For 2D matrices, it cuts the rows apart.

```python
# Split into 2 equal parts along the rows
top, bottom = np.vsplit(arr, 2)
```

### 3. Custom Splitting Locations
Instead of passing an integer for equal parts, you can pass a list of indices to split at specific exact positions.

```python
arr = np.array([10, 20, 30, 40, 50, 60])

# Split at index 2 and index 5
part1, part2, part3 = np.split(arr, [2, 5])
# Output:, [30, 40, 50], [60]
```
