## Question 1:
Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np
arr1 = np.zeros((10))
arr1[4] = 1
print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Question 2:
Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
a = int(input("Enter number a: "))
b = int(input("Enter number b: "))
arr2 = np.random.random((a,b))
avg = np.mean(arr2)
print(arr2)
print(avg)

[[0.93904761 0.18758146 0.27830395 0.90112126]
 [0.61678935 0.58745999 0.93458305 0.85258632]
 [0.1788683  0.85885143 0.91195168 0.62324324]]
0.6558656382314029


## Question 3:
Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.
Eg.-

[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]

In [8]:
a = int(input("Enter number a: "))
b = int(input("Enter number b: "))

arr3 = np.ones((a,b))
arr3[1:-1, 1:-1] = 0
print(arr3)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Question 4:
Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [10]:
arr4 = np.linspace(0,1,10) [1:-1]
print(arr4)

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


## Question 5:
 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [11]:
identity_matrix = np.eye(3,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## Question 6:
Create a 5x5 matrix with row values ranging from 0 to 4.

In [12]:
arr5 = np.linspace(0, 4, 25).reshape(5, 5)
print(arr5)

[[0.         0.16666667 0.33333333 0.5        0.66666667]
 [0.83333333 1.         1.16666667 1.33333333 1.5       ]
 [1.66666667 1.83333333 2.         2.16666667 2.33333333]
 [2.5        2.66666667 2.83333333 3.         3.16666667]
 [3.33333333 3.5        3.66666667 3.83333333 4.        ]]


## Question 7:
Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [20]:
arr = np.random.randint(1, 101, size=(10,2))

given_points = np.array([50, 50])

distance_from_given_points = np.linalg.norm(arr - given_points, axis=1)

distance = distance_from_given_points.astype(int)

print(distance)

[52 10 51 32 50 28 39 43 41 30]


## Question 8:
Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [4]:
arr = np.arange(336).reshape(6, 7, 8)
print(np.argwhere(arr == 100))

[[1 5 4]]
